CREATE TABLE category (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(100) NOT NULL,
                          code VARCHAR(50) NOT NULL,
                          label VARCHAR(100) NOT NULL,
                          CONSTRAINT uk_category_code UNIQUE (code)
);

CREATE TABLE uploaded_file (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               mime_type VARCHAR(255),
                               file_name VARCHAR(255),
                               url VARCHAR(255),
                               size INTEGER
);

CREATE TABLE wish (
                      wish_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      wish_name VARCHAR(150) NOT NULL,
                      wish_price DOUBLE PRECISION NOT NULL,
                      url VARCHAR(500),
                      status VARCHAR(20) NOT NULL,
                      category_id BIGINT NOT NULL,
                      priority VARCHAR(20) NOT NULL,

                      CONSTRAINT fk_wish_category
                          FOREIGN KEY (category_id)
                              REFERENCES category (id),

                      CONSTRAINT chk_wish_status
                          CHECK (status IN ('ACTIVE')),

                      CONSTRAINT chk_wish_priority
                          CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH'))
);